backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files: 
      - name: blog_settings
        label: Blog settings
        file: blog_settings.yml
        fields: 
          - name: categories
            widget: list
            summary: '{{fields.name}}'
            fields:
              - {name: name}  
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - label: "Categories"
        name: "categories"
        widget: "relation"
        required: false
        multiple: true
        collection: categories
        value_field: category
        search_fields: ['name']
      - label: Category2
        name: category2
        widget: relation
        collection: settings
        file: blog_settings
        value_field: categories.*.name
        search_fields: [categories.*.name]
        display_fields: [categories.*.name]        

  - name: categories
    label: Categories
    folder: categories
    create: true
    fields:
      - widget: string
        name: category
        label: Category
        required: true
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
